### ISSUE TITLE
have one file per scenario

### ISSUE THREAD

**Issue by sishtiaq** [project-everest/ci-logs#1]
Why not have one history file per scenario (fstar, mitls, etc), rather than a file per run? Currently, there's lots of one-history-point files. Doing a comparison could be a matter of doing a git diff of the file's history, rather than a diff of different files. 
The number of files will just grow: github's web UI already refuses to display >100.

**Comment by msprotz** [comment]
See also: https://github.com/project-everest/everest-ci/issues/22

This means that notifications would have to change the URL to the logs -- also, I'm wondering what would happens with usernames, branches, etc.
